# local_backend: true

backend:
  # name: proxy
  # proxy_url: http://localhost:8081/api/v1
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

editor:
  preview: false

# slug:
#   encoding: "ascii"
#   clean_accents: true
#   sanitize_replacement: "_"

collections:
  - name: "spectacles"
    label: "Spectacles"
    folder: "content/spectacles"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Year", name: "year", widget: "string" }
      - label: "Navigation"
        name: "navigation"
        widget: "object"
        fields:
          - {
              label: "Order",
              name: "order",
              widget: "number",
              default: 0,
              min: 0,
            }
      - label: "Images"
        name: "images"
        minimize_collapsed: true
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Caption", name: "caption", widget: "string" }

      - label: "Dates"
        name: "dates"
        minimize_collapsed: true
        widget: "list"
        fields:
          - { label: "Theatre Text", name: "theatre_text", widget: "string" }
          - { label: "Date Text", name: "date_text", widget: "string" }
          - {
              label: "Dates URL",
              name: "dates_url",
              widget: "string",
              required: false,
            }
          - {
              label: "Ticket URL",
              name: "ticket_url",
              widget: "string",
              required: false,
            }
          - { label: "Date Start", name: "date_start", widget: "datetime" }
          - { label: "Date End", name: "date_end", widget: "datetime" }
      - {
          label: "Credits",
          hint: "Toutes les autres parties, crédits, presse etc" name: "credits",
          widget: "markdown",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "collectif"
        label: "Collectif"
        file: "content/collectif.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - label: "Images"
            name: "images"
            widget: "list"
            minimize_collapsed: true
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string" }

          - label: "People"
            name: "people"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "contact"
        label: "Contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - label: "Images"
            name: "images"
            minimize_collapsed: true
            widget: "list"
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string" }

          - { label: "Body", name: "body", widget: "markdown" }
